### PR TITLE
plotTemporalSymmetry

### PR DESCRIPTION
**Pull request by KimLopezGuell**
Part of issue #75

### CODE REVIEW

**Comment by daniellenewby** [comment]
> Some things to consider:
> 
> * The function is very simple, it could offer more flexibility for the plot. Right now the user can choose the width of the x axis (from what month to what month to plot), the colours of both parts pre- and post- time 0, and what counts to censor. But I am happy to add more things for the user to be able to change (e.g. axis names, title...). It also plots all combinations of the marker/index available in the table, but maybe we could add a variable to restrict that to cohorts of interest (obviously the users can do that themselves as well).
> * The plots are "scale_free" so that they are all visible, but maybe you would like it not to be the case, to compare different drugs in absolute terms, even if some scales become minuscule?
> * Maybe you would like to offer the option to change the timescale to years or days?
> 
> You tell me @xihang-chen @daniellenewby or any other request

Hey @KimLopezGuell great work and thanks for doing it so quickly! can you show a couple of screenshots of the plots as it will make it easier to answer some of the questions. Yes to option to change the time scale and axis names, title and to add a restiction to what to plot. What is the function for time 0? do you mean what colour is the line at time 0? also not sure what the function is about what counts to censor? Thanks :)

**Comment by KimLopezGuell** [comment]
Okay, Danielle! I will add the option to put the time scale to "days" or "years", change axis names or plot title and to decide which index and marker ids to plot.
What I mean with colour is which two colours the plot will have (time > 0 and time < 0). As for censoring, I just thought that because all of these are counts, maybe some people need to censor some (<5) so I put the option in there. If this is done before at another analysis stage I can delete it.
This is an example with omock data of the plot as is now, doing
plotTemporalSymmetry(cdm, "joined_cohort", colours = c("purple2", "lightpink"), xlim = c(-20, 20))

image

**Comment by daniellenewby** [comment]
> Okay, Danielle! I will add the option to put the time scale to "days" or "years", change axis names or plot title and to decide which index and marker ids to plot. What I mean with colour is which two colours the plot will have (time > 0 and time < 0). As for censoring, I just thought that because all of these are counts, maybe some people need to censor some (<5) so I put the option in there. If this is done before at another analysis stage I can delete it. This is an example with omock data of the plot as is now, doing plotTemporalSymmetry(cdm, "joined_cohort", colours = c("purple2", "lightpink"), xlim = c(-20, 20))
> 
> image

Ok this looks amazing! Yep makes sense. Hmm not sure about the censor just make sure it hasnt been done before the results are fed to the plot?  Can a user add on additional layers to change the theme of the plot for example? so not having a grey background, making the x and y axis with black lines etc

**Comment by KimLopezGuell** [comment]
@daniellenewby I have added all the functionality you asked for. I also added the option to change the y scale to "free" or "fixed" because it seemed like a useful feature to me.
I will see if I can add an options kind of input that is more flexible so that the users can change the theme at their leisure.

I don't see a minCellCount argument or similar anywhere, but I agree that maybe it should be included before. I can take it out and open an issue about it? @xihang-chen

**Comment by KimLopezGuell** [comment]
@xihang-chen censorRange (minimum cell counts) deleted.
Also added the plotSequenceRatio with the specifications requested in #75

**Pull request merged**
